locale: "pl"

purger:
  enabled: true
  max-not-online-days: 90

default-title:
  enabled: true
  title-name: "example"

database:
  type: "sqlite"
  settings:
    sqlite:
      file-location: "%plugin-folder%/database.db"
    mysql:
      host: "localhost"
      port: "3306"
      database: "Mox_TokenShop"
      user: "root"
      password: "password"

titles:
  example:
    title: "&e&o[&7Example&8Title&e&o]&r"
    permission: "example.permission"
    gui-item:
      material: "BOOK"
      data: 0
      amount: 1
      name: "%default-name%" #Placeholders: %default-name%, %default-lore% ,%title%, %permission%, %player%, %selection%
      lore: "%selection%"
      glow: false
