locale: "pl"

titles:
  example:
    title: "&e&o[&7Example&8Title&e&o] &r"
    permission: "example.permission"

purger:
  enabled: true
  max-not-online-days: 90

default-title:
  enabled: true
  title-name: "example"

database:
  type: "sqlite"
  settings:
    sqlite:
      file-location: "%plugin-folder%/database.db"
    mysql:
      host: "localhost"
      port: "3306"
      database: "Mox_TokenShop"
      user: "root"
      password: "password"
