name: MoxChatTitles
author: Morkazoid
version: 1.1
depend: [MoxCore]
softdepend: [MVdWPlaceholderAPI, PlaceholderAPI]
description: "Morkazoids premium chat prefixes (titles) plugin. Created for GC2.PL Network"
main: com.morkaz.moxchattitles.MoxChatTitles
api-version: 1.13